### ISSUE TITLE
el-table 宽度足够时莫名出现水平滚动条

### ISSUE THREAD

**Issue by SuperAL** [SuperAL/issues-collection#1]
## 问题
el-table 宽度足够时（table style width:100%）莫名出现水平滚动条

## 参考
[Table width 100% is off by a single pixel (depending on actual width)
](https://stackoverflow.com/questions/23563162/table-width-100-is-off-by-a-single-pixel-depending-on-actual-width)
> I simply removed the width on the .table class, and relaced it with DISPLAY:block

Demo: http://jsfiddle.net/E2mUQ/3/

## 解决
我新增了样式：
```css
.el-table__body-wrapper table {
  display: block;
}
```
